Project: Restaurant Page
OlukaDenis/restaurant-page pull request #2
Opened 2020-04-22 19:15 UTC by OlukaDenis

- Using Webpack
- Creating DOM elements with Javascript

2020-04-23 00:07 UTC, bellom requested changes
## Hi @OlukaDenis  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-04-23 00:07 UTC, bellom commented on dist/index.html
> +
I guess you missed this; we are supposed to have just this 👉  `<div class="content" id="content"></div>'

According to the Odin project instructions: 
![image](https://user-images.githubusercontent.com/31897434/80043374-700f5e80-84f9-11ea-8744-9dd7f4e7cc8d.png)
https://www.theodinproject.com/courses/javascript/lessons/restaurant-page

2020-04-23 00:07 UTC, bellom commented on package.json
> +    "webpack-cli": "^3.3.11"
![image](https://user-images.githubusercontent.com/31897434/80044625-0002d780-84fd-11ea-9bb6-2b7d8d267e2d.png)
You are missing -> `webpack-dev-server`
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/

2020-04-23 00:07 UTC, bellom commented on package.json
> +    "start": "webpack --watch --mode development"
`npm start` seems not to open the server.
Let's try this
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open"
  },
```

2020-04-24 15:34 UTC, jofer86 approved these changes
## :wave: :wave: Hello!, I'm Jorge, and  I'm here to review this Pull Request, let's take a look shall we :eye: :eye: :eye: 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- All required changes were tackled!! Great Job!!!
# `status: Approved!!` :+1: :rocket: :rocket: 


--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

2020-04-24 17:52 UTC, OlukaDenis commented
Thanks

2020-04-24 18:04 UTC, merged